In [2]:

from google.colab  import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

# ระบุพาธไปยังไฟล์ CSV ใน Google Drive ของคุณ
file_path = '/content/drive/MyDrive/Colab Notebooks/เเบบประเมินความพึ่งพอใจของผู้ใช้งาน .csv'

# โหลดข้อมูลเข้าสู่ DataFrame
df = pd.read_csv(file_path)

# แสดงข้อมูล 5 แถวแรก
display(df.head())

,ประทับเวลา,1. เพศ,2. ช่วงอายุ,3. ระดับการศึกษาปัจจุบัน,4. ท่านเป็นผู้เรียนภาษาไทยในฐานะภาษาต่างประเทศ (ชาวต่างชาติ) หรือไม่,5. ท่านเคยใช้แอปพลิเคชันฝึกออกเสียง/เรียนภาษาลักษณะนี้มาก่อนหรือไม่,2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน],2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [มีความสวยงามและเป็นระเบียบ],2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [การแสดงผลสองภาษา (ไทย/อังกฤษ) ชัดเจน],2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [รูปเเบบตัวอักษร อ่านง่ายเเละสวยงาม],...,2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [จำแนกเสียงสระได้ถูกต้องแม่นยำ],2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ผลป้อนกลับ (Feedback) ชัดเจน เข้าใจง่าย],2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ประมวลผลและแสดงผลได้รวดเร็ว],2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยให้ออกเสียงสระภาษาไทยได้ถูกต้องขึ้น],2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยเพิ่มความมั่นใจในการออกเสียง],2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [สร้างแรงจูงใจให้ฝึกฝนอย่างต่อเนื่อง],2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [มีประโยชน์ต่อการเรียนรู้การออกเสียงภาษาไทย],2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [นำไปปรับใช้ในการออกเสียงในชีวิตประจำวัน],1. ปัญหาหรืออุปสรรคที่ท่านพบระหว่างการใช้งานแอปพลิเคชัน,2. ข้อเสนอแนะเพื่อการปรับปรุงแอปพลิเคชัน
0,"14/7/2026, 12:00:59",ชาย,ต่ำกว่า 18 ปี,มัธยมศึกษา/เทียบเท่า,ไม่ใช่,เคย,มากที่สุด,มาก,มากที่สุด,มากที่สุด,...,มาก,มาก,มากที่สุด,มาก,มาก,มาก,มากที่สุด,มาก,ไม่มี,ผมรักพี่ซันครับ
1,"14/7/2026, 12:06:23",ชาย,18–25 ปี,ปริญญาตรี,ไม่ใช่,ไม่เคย,มาก,มาก,มากที่สุด,มากที่สุด,...,มากที่สุด,มาก,มากที่สุด,มาก,มากที่สุด,มากที่สุด,มากที่สุด,มากที่สุด,—,—
2,"14/7/2026, 12:35:33",ชาย,26–35 ปี,ปริญญาตรี,ไม่ใช่,เคย,มากที่สุด,มากที่สุด,มาก,มากที่สุด,...,มากที่สุด,มากที่สุด,มากที่สุด,มากที่สุด,มากที่สุด,มากที่สุด,มากที่สุด,มากที่สุด,NaN,NaN
3,"14/7/2026, 12:49:47",ชาย,18–25 ปี,ปริญญาตรี,ไม่ใช่,เคย,ปานกลาง,มาก,ปานกลาง,ปานกลาง,...,น้อย,ปานกลาง,มาก,ปานกลาง,มาก,ปานกลาง,มาก,ปานกลาง,NaN,NaN
4,"14/7/2026, 13:25:35",หญิง,18–25 ปี,ปริญญาตรี,ไม่ใช่,ไม่เคย,มาก,มาก,มาก,มาก,...,มาก,มาก,มาก,มาก,มาก,มาก,มาก,มาก,-,-

In [4]:
# สร้างคอลัมน์ใหม่เพื่อจัดกลุ่มตามเงื่อนไขที่กำหนด
df['กลุ่มอายุ_ใหม่'] = df['2. ช่วงอายุ'].apply(lambda x: 'ต่ำกว่า 18 ปี' if str(x).strip() == 'ต่ำกว่า 18 ปี' else 'ไม่ใช่ต่ำกว่า 18 ปี')

# แสดงจำนวนข้อมูลของแต่ละกลุ่ม
age_group_counts = df.groupby('กลุ่มอายุ_ใหม่').size().reset_index(name='จำนวนผู้ตอบแบบประเมิน')
display(age_group_counts)

        กลุ่มอายุ_ใหม่  จำนวนผู้ตอบแบบประเมิน
0        ต่ำกว่า 18 ปี                     15
1  ไม่ใช่ต่ำกว่า 18 ปี                     34

In [5]:
# แสดงรายชื่อคอลัมน์ทั้งหมดใน DataFrame
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

1. ประทับเวลา
2. 1. เพศ
3. 2. ช่วงอายุ
4. 3. ระดับการศึกษาปัจจุบัน
5. 4. ท่านเป็นผู้เรียนภาษาไทยในฐานะภาษาต่างประเทศ (ชาวต่างชาติ) หรือไม่
6. 5. ท่านเคยใช้แอปพลิเคชันฝึกออกเสียง/เรียนภาษาลักษณะนี้มาก่อนหรือไม่
7. 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน]
8. 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [มีความสวยงามและเป็นระเบียบ]
9. 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [การแสดงผลสองภาษา (ไทย/อังกฤษ) ชัดเจน]
10. 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [รูปเเบบตัวอักษร อ่านง่ายเเละสวยงาม]
11. 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ความถูกต้องครบถ้วนของข้อมูล]
12. 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [จำแนกเสียงสระได้ถูกต้องแม่นยำ]
13. 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ผลป้อนกลับ (Feedback) ชัดเจน เข้าใจง่าย]
14. 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ประมวลผลและแสดงผลได้รวดเร็ว]
15. 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยให้ออกเสียงสระภาษาไทยได้ถูกต้องขึ้น]
16. 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยเพิ่มความมั่นใจในการออกเสียง]
17. 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [สร้างแรงจูงใจให้ฝึกฝนอย่างต่อเนื่อง]
18. 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [มีประโยชน์ต่อการเรียนรู้การออกเสียงภาษาไทย]
19. 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [นำไปปรับใช้ในการออกเสียงในชีวิตประจำวัน]
20. 1. ปัญหาหรืออุปสรรคที่ท่านพบระหว่างการใช้งานแอปพลิเคชัน
21. 2. ข้อเสนอแนะเพื่อการปรับปรุงแอปพลิเคชัน
22. กลุ่มอายุ_ใหม่

In [6]:
# ตรวจสอบข้อมูลที่เป็นไปได้ทั้งหมด (Unique values) ในคอลัมน์ที่ต้องการ
target_column = '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน]'
unique_values = df[target_column].dropna().unique()

print(f"ตัวเลือกที่มีอยู่ในคอลัมน์ '{target_column}':")
for val in unique_values:
    print(f"- {val}")

ตัวเลือกที่มีอยู่ในคอลัมน์ '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน]':
- มากที่สุด
- มาก
- ปานกลาง

In [7]:
# คำนวณความถี่ของตัวเลือกในแต่ละกลุ่มอายุ
target_column = '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน]'
result_table = pd.crosstab(df['กลุ่มอายุ_ใหม่'], df[target_column])

# แสดงตารางผลลัพธ์
display(result_table)

2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,1,13
ไม่ใช่ต่ำกว่า 18 ปี,3,12,19

In [8]:
# รายชื่อคอลัมน์ประเมินผลทั้งหมด (คอลัมน์ที่ 7 ถึง 19)
evaluation_cols = [
    '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน]',
    '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [มีความสวยงามและเป็นระเบียบ]',
    '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [การแสดงผลสองภาษา (ไทย/อังกฤษ) ชัดเจน]',
    '2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [รูปเเบบตัวอักษร อ่านง่ายเเละสวยงาม]',
    '2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ความถูกต้องครบถ้วนของข้อมูล]',
    '2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [จำแนกเสียงสระได้ถูกต้องแม่นยำ]',
    '2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ผลป้อนกลับ (Feedback) ชัดเจน เข้าใจง่าย]',
    '2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ประมวลผลและแสดงผลได้รวดเร็ว]',
    '2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยให้ออกเสียงสระภาษาไทยได้ถูกต้องขึ้น]',
    '2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยเพิ่มความมั่นใจในการออกเสียง]',
    '2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [สร้างแรงจูงใจให้ฝึกฝนอย่างต่อเนื่อง]',
    '2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [มีประโยชน์ต่อการเรียนรู้การออกเสียงภาษาไทย]',
    '2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [นำไปปรับใช้ในการออกเสียงในชีวิตประจำวัน]'
]

# วนลูปเพื่อหาความถี่ของแต่ละคำตอบแยกตามกลุ่มอายุในทุกคอลัมน์
for i, col in enumerate(evaluation_cols, 7):
    if col in df.columns:
        print(f"\n--- ตารางที่ {i}: {col} ---")
        ct = pd.crosstab(df['กลุ่มอายุ_ใหม่'], df[col])
        display(ct)

--- ตารางที่ 7: 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน] ---

2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [ใช้งานง่าย ไม่ซับซ้อน],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,1,13
ไม่ใช่ต่ำกว่า 18 ปี,3,12,19

--- ตารางที่ 8: 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [มีความสวยงามและเป็นระเบียบ] ---

2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [มีความสวยงามและเป็นระเบียบ],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,2,4,9
ไม่ใช่ต่ำกว่า 18 ปี,0,15,19

--- ตารางที่ 9: 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [การแสดงผลสองภาษา (ไทย/อังกฤษ) ชัดเจน] ---

2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [การแสดงผลสองภาษา (ไทย/อังกฤษ) ชัดเจน],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,2,3,10
ไม่ใช่ต่ำกว่า 18 ปี,3,15,16

--- ตารางที่ 10: 2.1  ด้านการใช้งานและการออกแบบ (Usability & UI Design) [รูปเเบบตัวอักษร อ่านง่ายเเละสวยงาม] ---

2.1 ด้านการใช้งานและการออกแบบ (Usability & UI Design) [รูปเเบบตัวอักษร อ่านง่ายเเละสวยงาม],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,2,0,13
ไม่ใช่ต่ำกว่า 18 ปี,3,11,20

--- ตารางที่ 11: 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ความถูกต้องครบถ้วนของข้อมูล] ---

2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ความถูกต้องครบถ้วนของข้อมูล],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,3,11
ไม่ใช่ต่ำกว่า 18 ปี,4,14,16

--- ตารางที่ 12: 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [จำแนกเสียงสระได้ถูกต้องแม่นยำ] ---

2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [จำแนกเสียงสระได้ถูกต้องแม่นยำ],น้อย,ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,,
ต่ำกว่า 18 ปี,0,1,5,9
ไม่ใช่ต่ำกว่า 18 ปี,1,2,16,15

--- ตารางที่ 13: 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ผลป้อนกลับ (Feedback) ชัดเจน เข้าใจง่าย] ---

2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ผลป้อนกลับ (Feedback) ชัดเจน เข้าใจง่าย],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,5,9
ไม่ใช่ต่ำกว่า 18 ปี,2,15,17

--- ตารางที่ 14: 2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ประมวลผลและแสดงผลได้รวดเร็ว] ---

2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (System Accuracy & Performance) [ประมวลผลและแสดงผลได้รวดเร็ว],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,2,3,10
ไม่ใช่ต่ำกว่า 18 ปี,1,15,18

--- ตารางที่ 15: 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยให้ออกเสียงสระภาษาไทยได้ถูกต้องขึ้น] ---

2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยให้ออกเสียงสระภาษาไทยได้ถูกต้องขึ้น],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,2,12
ไม่ใช่ต่ำกว่า 18 ปี,1,14,19

--- ตารางที่ 16: 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยเพิ่มความมั่นใจในการออกเสียง] ---

2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [ช่วยเพิ่มความมั่นใจในการออกเสียง],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,3,11
ไม่ใช่ต่ำกว่า 18 ปี,1,16,17

--- ตารางที่ 17: 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [สร้างแรงจูงใจให้ฝึกฝนอย่างต่อเนื่อง] ---

2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [สร้างแรงจูงใจให้ฝึกฝนอย่างต่อเนื่อง],น้อย,ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,,
ต่ำกว่า 18 ปี,0,1,3,11
ไม่ใช่ต่ำกว่า 18 ปี,1,5,14,14

--- ตารางที่ 18: 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [มีประโยชน์ต่อการเรียนรู้การออกเสียงภาษาไทย] ---

2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [มีประโยชน์ต่อการเรียนรู้การออกเสียงภาษาไทย],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,2,12
ไม่ใช่ต่ำกว่า 18 ปี,0,17,17

--- ตารางที่ 19: 2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [นำไปปรับใช้ในการออกเสียงในชีวิตประจำวัน] ---

2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effectiveness) [นำไปปรับใช้ในการออกเสียงในชีวิตประจำวัน],ปานกลาง,มาก,มากที่สุด
กลุ่มอายุ_ใหม่,,,
ต่ำกว่า 18 ปี,1,2,12
ไม่ใช่ต่ำกว่า 18 ปี,1,17,16

In [10]:
import pandas as pd
from scipy.stats import chi2_contingency

results = []

for col in evaluation_cols:
    if col in df.columns:
        # สร้าง Contingency Table ระหว่างกลุ่มอายุกับข้อคำถามนั้นๆ
        contingency_table = pd.crosstab(df['กลุ่มอายุ_ใหม่'], df[col])

        try:
            chi2, p_val, dof, expected = chi2_contingency(contingency_table)
            results.append({
                'ข้อประเมิน': col,
                'Chi-Square': round(chi2, 4),
                'p-value': round(p_val, 4),
                'd.f.': dof,
                'มีนัยสำคัญ (p < 0.05)': 'ใช่' if p_val < 0.05 else 'ไม่ใช่'
            })
        except Exception as e:
            results.append({
                'ข้อประเมิน': col,
                'Chi-Square': None,
                'p-value': None,
                'd.f.': None,
                'มีนัยสำคัญ (p < 0.05)': f'ข้อผิดพลาด: {str(e)}'
            })

# แปลงเป็น DataFrame เพื่อการแสดงผลที่สวยงาม
chi_square_summary = pd.DataFrame(results)
display(chi_square_summary)

,ข้อประเมิน,Chi-Square,p-value,d.f.,มีนัยสำคัญ (p < 0.05)
0,2.1 ด้านการใช้งานและการออกแบบ (Usability & UI...,4.7848,0.0914,2,ไม่ใช่
1,2.1 ด้านการใช้งานและการออกแบบ (Usability & UI...,5.3817,0.0678,2,ไม่ใช่
2,2.1 ด้านการใช้งานและการออกแบบ (Usability & UI...,2.6096,0.2712,2,ไม่ใช่
3,2.1 ด้านการใช้งานและการออกแบบ (Usability & UI...,6.2585,0.0438,2,ใช่
4,2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (Syst...,2.9144,0.2329,2,ไม่ใช่
5,2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (Syst...,1.4452,0.6950,3,ไม่ใช่
6,2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (Syst...,0.5032,0.7776,2,ไม่ใช่
7,2.2 ด้านความถูกต้องและประสิทธิภาพของระบบ (Syst...,3.8271,0.1476,2,ไม่ใช่
8,2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effec...,3.7819,0.1509,2,ไม่ใช่
9,2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effec...,3.3109,0.1910,2,ไม่ใช่
10,2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effec...,4.4453,0.2172,3,ไม่ใช่
11,2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effec...,7.4582,0.0240,2,ใช่
12,2.3 ด้านประโยชน์ต่อการเรียนรู้ (Learning Effec...,5.9392,0.0513,2,ไม่ใช่